name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install backend dependencies
      run: npm install
    
    - name: Install frontend dependencies and build
      run: |
        cd frontend
        npm install
        npm run build
        cd ..
    
    - name: Copy build to backend
      run: |
        mkdir -p public
        cp -r frontend/build/* public/
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-name'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
